version: "3.8"

services:
  api_db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: api_db  
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - api_db

