"""make name, review, comment non-nullable

Revision ID: 83a68205e100
Revises: 14f346e5e8f2
Create Date: 2025-09-24 14:27:36.023010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83a68205e100'
down_revision: Union[str, Sequence[str], None] = '14f346e5e8f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('review', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('review', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('review', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
