"""change duration minutes to interval

Revision ID: eb9e0914ea46
Revises: 88054480be54
Create Date: 2025-09-23 23:33:47.002931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb9e0914ea46'
down_revision: Union[str, Sequence[str], None] = '88054480be54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('service', 'duration_minutes',
#                existing_type=sa.INTEGER(),
#                type_=sa.Interval(),
#                existing_nullable=False)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('service', 'duration_minutes',
#                existing_type=sa.Interval(),
#                type_=sa.INTEGER(),
#                existing_nullable=False)
#     # ### end Alembic commands ###


def upgrade() -> None:
    """Upgrade schema."""
    # Convert integer minutes to interval
    op.execute(
        "ALTER TABLE service ALTER COLUMN duration_minutes TYPE INTERVAL USING (duration_minutes * INTERVAL '1 minute')"
    )

def downgrade() -> None:
    """Downgrade schema."""
    # Convert interval back to integer minutes
    op.execute(
        "ALTER TABLE service ALTER COLUMN duration_minutes TYPE INTEGER USING EXTRACT(EPOCH FROM duration_minutes)/60"
    )


